### ISSUE TITLE
Update composer intro docker container

### ISSUE THREAD

**Issue by annielmenezes** [azukiapp/docker-php-fpm#3]
When I use:

``` bash
$ azk shell --image azukiapp/php-fpm --shell /bin/bash
# composer create-project laravel/laravel my-app --prefer-dist
# exit
```

The container returns an warning needing to update Composer
`Warning: This development build of composer is over 60 days old. It is recommended to update it by running "/usr/local/bin/composer self-update" to get the latest version.`

You could update the version 5.6 of the container, please?

**Comment by gullitmiranda** [comment]
I'm sorry for the delay in replying. A few days update the image.

But we are intending to redo these images using the [alpine](https://hub.docker.com/r/azukiapp/alpine/).
